M48
; DRILL file {KiCad 9.0.0-9.0.0-2~ubuntu24.04.1} date 2025-03-08T17:31:21+0000
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-03-08T17:31:21+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0-9.0.0-2~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0827
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1378
%
G90
G05
T1
X1.839Y-1.739
X2.2878Y-1.739
T2
X3.9768Y-1.8138
X4.5768Y-1.8138
T3
X4.2323Y-4.3949
M30
